#!/bin/bash

# Script to remove the unused common component imports we just added

FILES=(
  "/Users/eko3/limn-systems-enterprise/src/app/admin/activity/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/analytics/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/approvals/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/dashboard/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/export/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/roles/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/settings/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/admin/users/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/auth/contractor/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/auth/customer/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/auth/dev/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/auth/employee/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/crm/orders/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/crm/projects/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboard/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/analytics/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/design/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/executive/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/financial/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/manufacturing/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/partners/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/projects/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/quality/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/dashboards/shipping/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/design/boards/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/design/briefs/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/design/documents/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/documents/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/financials/invoices/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/financials/payments/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/partners/designers/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/partners/factories/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/designer/documents/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/designer/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/designer/quality/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/designer/settings/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/documents/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/factory/documents/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/factory/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/factory/quality/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/factory/settings/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/financials/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/orders/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/portal/shipping/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/dashboard/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/factory-reviews/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/ordered-items/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/packing/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/qc/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/shop-drawings/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/production/shipments/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/products/collections/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/products/concepts/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/products/materials/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/products/ordered-items/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/products/prototypes/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/shipping/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/shipping/shipments/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/shipping/tracking/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/client/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/designer/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/kanban/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/manufacturer/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/my/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/tasks/templates/page.tsx"
  "/Users/eko3/limn-systems-enterprise/src/app/crm/page.tsx"
)

for file in "${FILES[@]}"; do
  if [ -f "$file" ]; then
    echo "Cleaning: $file"
    # Remove the common components import line
    sed -i '' '/^import { PageHeader, DataTable, StatsGrid, LoadingState, EmptyState, StatusBadge, InfoCard } from "@\/components\/common";$/d' "$file"
    echo "  ✓ Removed unused import"
  fi
done

echo "Cleanup complete!"
