/**
 * Flipbook Navigation Types
 *
 * Type definitions for Table of Contents and Thumbnail Navigation
 * Phase 1: TOC & Thumbnails Enhancement
 */

// ============================================================================
// TABLE OF CONTENTS TYPES
// ============================================================================

/**
 * Individual TOC item
 */
export interface TOCItem {
  /** Unique identifier for this TOC item */
  id: string;

  /** Display title */
  title: string;

  /** Target page number (1-indexed) */
  pageNumber: number;

  /** Hierarchical level (1-4, where 1 is top level) */
  level: 1 | 2 | 3 | 4;

  /** Sort order within the same level */
  sortOrder: number;

  /** Optional icon/emoji */
  icon?: string;

  /** Child items (nested structure) */
  children: TOCItem[];

  /** Optional metadata */
  metadata?: {
    /** Page count for this section */
    pageCount?: number;
    /** Last modified timestamp */
    lastModified?: string;
    /** Custom data */
    custom?: Record<string, unknown>;
  };
}

/**
 * Complete TOC data structure
 */
export interface TOCData {
  /** Root-level TOC items */
  items: TOCItem[];

  /** Whether TOC was auto-generated from PDF */
  autoGenerated: boolean;

  /** Last modification timestamp */
  lastModified: string;

  /** Version for backwards compatibility */
  version: string;
}

/**
 * TOC display settings
 */
export interface TOCSettings {
  /** Whether TOC is enabled */
  enabled: boolean;

  /** Panel position */
  position: 'left' | 'right' | 'floating';

  /** Whether TOC is expanded by default */
  defaultExpanded: boolean;

  /** Whether to show page numbers */
  showPageNumbers?: boolean;

  /** Whether to show icons */
  showIcons?: boolean;

  /** Whether to enable search */
  searchEnabled?: boolean;

  /** Whether to highlight current page */
  highlightCurrent?: boolean;

  /** Custom width in pixels */
  width?: number;
}

/**
 * TOC builder operations
 */
export interface TOCBuilderActions {
  /** Add new item */
  addItem: (_parentId: string | null, _item: Omit<TOCItem, 'id' | 'children'>) => void;

  /** Update existing item */
  updateItem: (_itemId: string, _updates: Partial<Omit<TOCItem, 'id' | 'children'>>) => void;

  /** Delete item */
  deleteItem: (_itemId: string, _deleteChildren: boolean) => void;

  /** Reorder items */
  reorderItems: (_itemIds: string[], _newParentId?: string | null) => void;

  /** Move item to different parent */
  moveItem: (_itemId: string, _newParentId: string | null, _newIndex: number) => void;

  /** Import TOC from external source */
  importTOC: (_data: TOCData | TOCItem[]) => void;

  /** Export TOC */
  exportTOC: (_format: 'json' | 'csv') => string | Blob;

  /** Clear all items */
  clearAll: () => void;

  /** Auto-generate from PDF */
  autoGenerate: () => Promise<void>;
}

// ============================================================================
// THUMBNAIL TYPES
// ============================================================================

/**
 * Thumbnail size variants
 */
export type ThumbnailSize = 'small' | 'medium' | 'large';

/**
 * Thumbnail data
 */
export interface ThumbnailData {
  /** Page ID */
  pageId: string;

  /** Page number */
  pageNumber: number;

  /** Standard thumbnail URL */
  url: string;

  /** Small thumbnail URL (for grid view) */
  smallUrl?: string;

  /** Generation timestamp */
  generatedAt: string;

  /** Thumbnail dimensions */
  dimensions?: {
    width: number;
    height: number;
  };
}

/**
 * Thumbnail display settings
 */
export interface ThumbnailSettings {
  /** Whether thumbnails are enabled */
  enabled: boolean;

  /** Position of thumbnail strip */
  position: 'bottom' | 'top' | 'left' | 'right' | 'grid';

  /** Thumbnail size */
  size: ThumbnailSize;

  /** Whether to show page numbers on thumbnails */
  showPageNumbers?: boolean;

  /** Whether to show page titles */
  showPageTitles?: boolean;

  /** Whether to highlight current page */
  highlightCurrent?: boolean;

  /** Whether to auto-scroll to current page */
  autoScroll?: boolean;

  /** Whether to enable hover preview */
  hoverPreview?: boolean;

  /** Gap between thumbnails in pixels */
  gap?: number;
}

/**
 * Thumbnail grid settings
 */
export interface ThumbnailGridSettings extends Omit<ThumbnailSettings, 'position'> {
  /** Number of columns (or 'auto' for responsive) */
  columns: number | 'auto';

  /** Whether to enable multi-select */
  multiSelect?: boolean;

  /** Whether to enable filtering */
  filtering?: boolean;

  /** Whether to enable sorting */
  sorting?: boolean;
}

// ============================================================================
// NAVIGATION SETTINGS (COMBINED)
// ============================================================================

/**
 * Complete navigation settings for a flipbook
 */
export interface NavigationSettings {
  /** Table of Contents settings */
  toc: TOCSettings;

  /** Thumbnail navigation settings */
  thumbnails: ThumbnailSettings;

  /** Additional navigation features */
  features?: {
    /** Enable page jump dialog */
    pageJump?: boolean;

    /** Enable keyboard shortcuts */
    keyboardShortcuts?: boolean;

    /** Enable mini-map */
    miniMap?: boolean;

    /** Enable breadcrumbs */
    breadcrumbs?: boolean;
  };
}

// ============================================================================
// PDF EXTRACTION TYPES
// ============================================================================

/**
 * PDF outline item (from PDF.js)
 */
export interface PDFOutlineItem {
  /** Title of the bookmark */
  title: string;

  /** Bold text */
  bold?: boolean;

  /** Italic text */
  italic?: boolean;

  /** Text color */
  color?: Uint8ClampedArray;

  /** Destination page reference */
  dest?: string | unknown[];

  /** URL link */
  url?: string | null;

  /** Child items */
  items?: PDFOutlineItem[];
}

/**
 * Result from PDF TOC extraction
 */
export interface PDFTOCExtractionResult {
  /** Extracted TOC items */
  items: TOCItem[];

  /** Whether extraction was successful */
  success: boolean;

  /** Number of items extracted */
  itemCount: number;

  /** Any errors encountered */
  errors?: string[];

  /** Warnings */
  warnings?: string[];
}

// ============================================================================
// EVENT TYPES
// ============================================================================

/**
 * TOC navigation event
 */
export interface TOCNavigationEvent {
  /** TOC item that was clicked */
  item: TOCItem;

  /** Target page number */
  pageNumber: number;

  /** Timestamp */
  timestamp: Date;

  /** Navigation method */
  method: 'click' | 'keyboard' | 'search';
}

/**
 * Thumbnail navigation event
 */
export interface ThumbnailNavigationEvent {
  /** Page that was selected */
  pageNumber: number;

  /** Thumbnail data */
  thumbnail: ThumbnailData;

  /** Timestamp */
  timestamp: Date;

  /** Navigation method */
  method: 'click' | 'keyboard' | 'hover';
}

// ============================================================================
// VALIDATION SCHEMAS (for Zod)
// ============================================================================

/**
 * TOC item validation rules
 */
export const TOC_VALIDATION = {
  /** Min/max title length */
  TITLE_MIN_LENGTH: 1,
  TITLE_MAX_LENGTH: 500,

  /** Min/max page number */
  PAGE_MIN: 1,
  PAGE_MAX: 9999,

  /** Min/max level */
  LEVEL_MIN: 1,
  LEVEL_MAX: 4,

  /** Max icon length (emoji) */
  ICON_MAX_LENGTH: 10,

  /** Max children depth */
  MAX_DEPTH: 4,

  /** Max items at any level */
  MAX_ITEMS_PER_LEVEL: 100,
} as const;

/**
 * Thumbnail validation rules
 */
export const THUMBNAIL_VALIDATION = {
  /** Standard thumbnail dimensions */
  STANDARD_WIDTH: 200,
  STANDARD_HEIGHT: 280,

  /** Small thumbnail dimensions */
  SMALL_WIDTH: 100,
  SMALL_HEIGHT: 140,

  /** Large thumbnail dimensions */
  LARGE_WIDTH: 300,
  LARGE_HEIGHT: 420,

  /** Image format */
  FORMAT: 'webp' as const,

  /** Quality (0-100) */
  QUALITY: 75,
} as const;
